name: worldmodel
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - torchvision
      - gymnasium
      - crafter
      - minigrid
      - pyyaml
      - tensorboard
      - mkdocs-material
      - numpy
      - pillow
      - -e .
