name: worldmodel
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - torchvision
      - "jax[cpu]"
      - craftax
      - pyyaml
      - tensorboard
      - mkdocs-material
      - numpy
      - pillow
      - imageio
      - -e .
